02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/urls.py
from django.urls import path
from catalog import views


# URL을 받아서 필요한 처리를 해주기 위해서는 
# urls.py에 반드시 urlpatterns라는 리스트가 필요하다
# path에 이름을 지정하면 <a href="{% url 'index'%}"> 형태로 지정이 가능
urlpatterns = [
    # /catalog/ > 함수로 지정
    path("", views.index, name = "index"),
    # /catalog/books/ > 클래스로 생성
    path("books", views.BookListView.as_view(), name = "books"),
    # /catalog/book/??? > 클래스로 생성
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    # /catalog/authors/ > 클래스로 생성
    path("authors", views.AuthorListView.as_view(), name = "authors"),
    # /catalog/book/??? > 클래스로 생성
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
    path("mybooks", views.LoanedBooksByUserListView.as_view(), name = "my-borrowed"),
    path("book/<uuid:pk>/renew/", views.renew_book_librarian, name= "renew-book-librarian"),

    path("borrowed", views.AllBorrowedBookListView.as_view(), name = "all-borrowed"),

    path("author/create/", views.AuthorCreate.as_view(), name = 'author-create'),
    path("author/<int:pk>/update/", views.AuthorCreate.as_view(), name = 'author-update'),
    path("author/<int:pk>/delete/", views.AuthorCreate.as_view(), name = 'author-delete'),


]

urlpatterns += [
    path("api/books/", views.BookListAPIView.as_view()),
    path("api/book_instances", views.BookinstanceAPIView.as_view())
]

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


# URL을 보내는 곳
urlpatterns = [
    path("admin/", admin.site.urls),
]
    # catalog > urls.py를 바라본다
urlpatterns += [
    path('catalog/', include('catalog.urls')),
    path("", RedirectView.as_view(url='/catalog/', permanent=True))
]

# 자바 스크립트를 사용하는 곳
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# 인증용 URL 만들기
urlpatterns += [
    path("accounts/",include("django.contrib.auth.urls"))
]

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from datetime import date

# 랜덤값을 만들어준다.
import uuid

# Create your models here.
# orm을 위한 객체를 정리하는 곳
# class User

class Genre(models.Model):
    # CharField = varchar(200)
    name = models.CharField(
        max_length=200, 
        help_text="Enter a book genre(e.g. SF)"
    )

    # print(genre) 이렇게 하면, genre.name이 출력되도록 합니다.
    def __str__(self):
        return self.name
    
class Book(models.Model):
    title = models.CharField(max_length=200)
    # ForeignKey 옵션은 외부 테이블과의 연관관계를 나타낸다.
    author = models.ForeignKey('Author',
    on_delete=models.SET_NULL,null=True)
    summary = models.TextField(max_length=1000,help_text='Enter a brief description of the book')
    isbn = models.CharField("ISBN",max_length=13,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])
    
    def display_genre(self):
        # data = []
        # for genre in self.genre.all():
        #     data += genre
        # return "," .join(data[:3])
        # 위 코드와 똑같습니다.
        return ", ".join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = "Genre"

class Bookinstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,
    help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey("Book", on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    # 데이터베이스 안에서 date값은 string
    due_back = models.DateField(null=True, blank=True)
    # AUTH_USER_MODEL > django에서 기본적으로 제공하는 유저 모델
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL, null=True, blank=True
    )

    # 공통코드
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),



        ('r', 'Reserved'),
    )


    #m, o, a, r 증에 하나만 허용
    status = models.CharField(
        max_length=1, 
        choices=LOAN_STATUS, 
        blank=True,
        default="m",
        help_text='Book availability',
        )

class Meta:
    ordering = ['due_back']
    permissions = (("can_mark_returned","Set book as returned"),)

def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


@property
def is_overdue(self):
    # 반납기한이 오늘보다 빠른가
    return bool(self.due_back and date.today()>self.due_back)
    





class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True,blank=True)
    date_of_death = models.DateField('Died',null=True,blank=True)
    

    class Meta:
        ordering = ["last_name","first_name"]

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        return f"{self.first_name}. {self.last_name}"
    
    

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class RenewBookform(forms.Form):
    renewal_date = forms.DateField(
        help_text = "Enter a date between now and 4 weeks (default 3)."
    )

    def clean_renewal_date(self):
        data = self.cleaned_data["renewal_date"]
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
        return data

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/views.py
from django.db.models.query import QuerySet
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404
from catalog.models import Book, Author, Bookinstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import datetime
from django.urls import reverse
from catalog.forms import RenewBookform
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from rest_framework.response import Response
from rest_framework.views import APIView
from catalog.serializers import BookSerializer, BookinstanceSerializer



# Create your views here.
# URL을 받아서 실제 뷰를 생성합니다.

# index라고하는 함수나 클래스가 필요함.


# Flask의 다음 함수와 같다.
# @app.route("~~~")
# def aaa():
#    return render_template()

# 함수형 뷰에서 로그인 정보를 체크하는 방법
# @login_
def index(request):

    # ?keyword=asdf 받을 수 있게 해야 한다.
    keyword = request.GET.get("keyword")

    # 세션을 가져오는 방법
    num_visits = request.session.get("num_visits",0)
    request.session["num_visits"] = num_visits + 1


    # Django ORM
    num_books = Book.objects.count()
    num_instances = Bookinstance.objects.all().count()
    # SELECT COUNT(1) FROM Bookinstance WHERE status = "a"
    num_instances_available = Bookinstance.objects.filter(status__exact="a").count()

    num_authors = Author.objects.count()

    # keyword로 장르와 책들의 개수를 가져온다.
    num_books_by_keyword = Book.objects.filter(title__exact=keyword).count()
    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_books_by_keyword": num_books_by_keyword,
    }

    return render(request, "index.html", context=context)

# LoginRequiredMixin > 이 클래스를 상속하면 로그인이 필요해진다
class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 5
    # template안에서 [model]_list 형태로 보여지게 된다.
    # context_object_name > 함수 view context
    # context_object_name = "my_book_list"
    # 모델이 보여지는 방식을 지정
    # queryset = Book.objects.all()[:5]

    # queryset은 다음과 같이 지정할수도 있습니다.
    # def get_queryset(self):
    #    return Book.objects.all()[:5]
    # template_name = "book_list.html"

    # context=context, context에 리턴할 데이터가 많을 경우
    # 다음 함수를 오버라이드 해서 필요한 데이터를
    # 추가로 넣어줄 수도 있습니다.
    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context["some_data"] = "just data"
        return context


# 클래스 기반의 디테일 뷰
class BookDetailView(generic.DetailView):
    model = Book


# 디테일 뷰를 함수로 변경했을 경우 다음과 같이 표현됩니다.
# def book_detail_view(request, pk):
#    try:
#        book = Book.objects.get(pk=pk)
#    except Book.DoesNotExist:
#        raise Http404("Book dose not exist")

# 리버스 검색
# Forienkey가 달려있지 않은 곳에서 연결된 리스트를 찾아주는 함수
#   book_instances = book.bookinstance_set.all()
#   return render(request, "catalog/book_detail.html", contenxt={"book", book})


# Author_list
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 5


# author_detail
class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = Bookinstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = 5
    def get_queryset(self):
        return (
            Bookinstance.objects.filter(borrower = self.request.user)
            .filter(status__exact = "o")
            .order_by("due_back")
        )

class AllBorrowedBookListView(LoginRequiredMixin,PermissionRequiredMixin, generic.ListView):
    model = Bookinstance
    template_name = "catalog/all_borrowed_book_list.html"
    # 관리자 유저일때만 사용 가능한 권한
    permission_required = "user.is_staff"

    def get_queryset(self):
        # borrower가 NULL이면 안됨
        # status가 o 이어야 함
        return (
            Bookinstance.objects.filter(borrower__isnull=False),filter(status__exact = "o")
        ).order_by("due_back")

@login_required
@permission_required("catalog.can_mark_returned", raise_exception=True)
def renew_book_librarian(request, pk):
    # pk에 해당하는 책 사본이 없으면 404에러
    book_instance = get_object_or_404(Bookinstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        # PSOT => 폼 자료체크 시작
        form = RenewBookform(request.POST)

        # Check if the form is valid:
        # 통과가 되었다면
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            # 데이터베이스에 데이터를 저장
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            # 대여 책 목록으로 이동
            return HttpResponseRedirect(reverse('books'))

    # If this is a GET (or any other method) create the default form.
    else:
        # Form에 기본값을 넣어준다
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookform(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    # GET 요청일 대만 책 대여기간 연장 폼으로 이동
    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    initial = {"date_of_death": "11/11/2024"}
    permission_required = "catalog.add_author"


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = "__all__"
    permission_required = "catalog.change_author"

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy("authors")
    permission_required = "catalog.delete_author"

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            reverse("author-delete", kwargs={"pk": self.object.pk})
    
# API를 리턴하기 위해서는 APIview를 상속받아야 합니다    
class BookListAPIView(APIView):
    # 상속 받았으면 get 메서드를 구현해야 합니다.
    def get(self, request):
        # 데이터를 쿼리
        books = Book.objects.all()
        # 시리얼라이징
        serializer = BookSerializer(books, many=True)
        # response 형태로 리턴
        return Response(serializer.data)
        
# 실습
# Book_instance가 있다
# Book id를 가져와서 id에 해당하는 Book_instance의 리스트를 가져오자

# Bookinstance를 DD로 변환


class BookinstanceAPIView(APIView):
    # get함수 : 실제 검색어에 맞는 데이터를 리턴
    def get(self, request):
        # 책 식별자를 받아옴
        book_id = request.GET["book_id"]
        Bookinstance.objects.filter(book__id__exact = book_id)
        serializer = BookinstanceSerializer(copy_list, many = True)


        return Response(serializer.data)
    
    # post 함수 받아온 데이터를 실제 데이터베이스에 적용
    def post(self, request):
        # request.data > 폼 데이터 안에 있는 데이터를 Model로 변경해줌
        serializer = BookSerializer(data=request.data)
        # 원하는 포맷을 통과했을때
        if serializer.is_valid():
            # Book 형태로 데이터가 변환 되었으므로 Book을 저장
            serializer.save()
            return Response(serializer.data)

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/all_borrowed_book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>All Borrowed books</h1>

  {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
          ({{ bookinst.due_back }})
        </li>
      {% endfor %}
    </ul>

  {% else %}
    <p>There are no books borrowed.</p>
  {% endif %}
{% endblock %}

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

  <h1>Delete Author:
    {{ author }}</h1>

  {% if author.book_set.all %}

    <p>You can't delete this author until all their books have been deleted:</p>
    <ul>
      {% for book in author.book_set.all %}
        <li>
          <a href="{% url 'book-detail' book.pk %}">{{book}}</a>
          ({{book.bookinstance_set.all.count}})</li>
      {% endfor %}
    </ul>

  {% else %}
    <p>Are you sure you want to delete the author?</p>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" action="" value="Yes, delete.">
    </form>
  {% endif %}

{% endblock %}

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  {% block sidebar %}
    {{ block.super }}

    {% if perms.catalog.change_author or perms.catalog.delete_author %}
      <hr>
      <ul class="sidebar-nav">
        {% if perms.catalog.change_author %}
          <li>
            <a href="{% url 'author-update' author.id %}">Update author</a>
          </li>
        {% endif %}
        {% if not author.book_set.all and perms.catalog.delete_author %}
          <li>
            <a href="{% url 'author-delete' author.id %}">Delete author</a>
          </li>
        {% endif %}
      </ul>
    {% endif %}

  {% endblock %}
  <h1>Author:
    {{ author.first_name }},
    {{ author.last_name }}
  </h1>

  <p>
    {{ author.date_of_birth }}
    ~
    {{ author.date_of_death }}
  </p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
      <strong>
        <a href="{{book.get_absolute_url}}">{{book.title}}</a>
      </strong>
      <p class="text-muted">
        {{book.summary}}
      </p>
    {% endfor %}
  </div>
{% endblock %}

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
    <!-- create랑 update는 기본적으로 form 템플릿을 같이 사용-->
    <!-- author-create랑 author-update가 이 템플릿을 같이 사용-->

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block title%}
  <title>Authors</title>
  {% endblock%}

  {% block content %}
    <h1>Author List</h1>
    {% if author_list %}
      <ul>
        {% for author in author_list %}
          <li>
            <a href="{{ author.get_absolute_url }}">{{ author.first_name }},
              {{author.last_name}}({{author.date_of_birth}}
              ~
              {{author.date_of_death}})</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %}
  {% endblock %}

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title:
    {{ book.title }}</h1>

  <p>
    <strong>Author:</strong>
    <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a>
  </p>
  <!-- author detail link not yet defined -->
  <p>
    <strong>Summary:</strong>
    {{ book.summary }}</p>
  <p>
    <strong>ISBN:</strong>
    {{ book.isbn }}</p>

  <p>
    <strong>Genre:</strong>
    {% for genre in book.genre.all %}
      {{ genre }}
      {% if not forloop.last %},
      {% endif %}
    {% endfor %}
  </p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p>
          <strong>Due to be returned:</strong>
          {{copy.due_back}}</p>
      {% endif %}
      <p>
        <strong>Imprint:</strong>
        {{copy.imprint}}</p>
      <p class="text-muted">
        <strong>Id:</strong>
        {{copy.id}}</p>

      {% if perms.catalog.can_mark_returned %}-
        <a href="{% url 'renew-book-librarian' copy.id %}">Renew</a>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %} >Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

02_Web_Programing/FRAMEWORKS/DJANGO/attempt/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}